spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mkdlp/LearnSpringCloud.git
          search-paths: config-repo
server:
  port: 12000
